# Generated by Django 4.0 on 2022-08-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_question', to='pages.option'),
        ),
    ]
