# Generated by Django 4.0 on 2022-08-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bookmarks_customuser_drafts_and_more'),
        ('pages', '0004_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to='accounts.CustomUser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_a_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='accounts.CustomUser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='no_of_times_played',
            field=models.IntegerField(default=0),
        ),
    ]
