# Generated by Django 4.0 on 2022-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bookmarks_customuser_drafts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_activated_account',
            field=models.BooleanField(default=False),
        ),
    ]
